site_name: Aishwarya Kaura
site_description: Designer • Creator • Explorer
site_url: https://aishwaryakaura.github.io/AK_WEBSITE_MDEF-REPO/
repo_url: https://github.com/aishwaryakaura/AK_WEBSITE_MDEF-REPO

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Contact: contact.md

theme:
  name: material
  logo: images/favicon.svg
  favicon: images/favicon.svg
  palette:
    primary: teal
    accent: cyan
  font:
    text: Poppins
    code: Cutive Mono
  features:
    - navigation.tabs
    - navigation.top
    - header.autohide

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - codehil
      fallback_to_build_date: true

# --------------------------
# MARKDOWN ENHANCEMENTS
# --------------------------
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

# --------------------------
# CUSTOM STYLES
# --------------------------
extra_css:
  - stylesheets/extra.css

